/******************************************************************************/
/***          Generated by IBExpert 2010.11.05 15.03.2011 14:46:49          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;

CREATE DATABASE 'D:\Front\FRONT_LOG.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 8192
DEFAULT CHARACTER SET WIN1251 COLLATION WIN1251;



/******************************************************************************/
/***                                Domains                                 ***/
/******************************************************************************/

CREATE DOMAIN DCURRENCY AS
DECIMAL(15,4);

CREATE DOMAIN DEDITIONDATE AS
TIMESTAMP
DEFAULT CURRENT_TIMESTAMP
;

CREATE DOMAIN DFOREIGNKEY AS
INTEGER;

CREATE DOMAIN DINTEGER_NOTNULL AS
INTEGER
NOT NULL;

CREATE DOMAIN DINTKEY AS
INTEGER
NOT NULL
CHECK (VALUE > 0);

CREATE DOMAIN DNAME AS
VARCHAR(60)
NOT NULL
COLLATE PXW_CYRL;

CREATE DOMAIN DTEXT40 AS
VARCHAR(40)
COLLATE PXW_CYRL;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GD_G_UNIQUE;
SET GENERATOR GD_G_UNIQUE TO 138;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE GD_EVENT (
    ID         DINTKEY NOT NULL,
    EVENTNAME  DNAME
);

CREATE TABLE GD_EVENTLOG (
    ID           DINTKEY NOT NULL,
    USERKEY      DFOREIGNKEY,
    EVENTKEY     DFOREIGNKEY,
    EDITIONDATE  DEDITIONDATE,
    ORDERKEY     DFOREIGNKEY,
    GOODLOGKEY   DFOREIGNKEY
);

CREATE TABLE GD_GOOD (
    ID        DINTKEY NOT NULL,
    GOODNAME  DNAME,
    GOODKEY   DINTEGER_NOTNULL
);

CREATE TABLE GD_GOODLOG (
    ID        DINTKEY NOT NULL,
    GOODKEY   DFOREIGNKEY,
    SUMM      DCURRENCY,
    QUANTITY  DCURRENCY
);

CREATE TABLE GD_ORDER (
    ID        DINTKEY NOT NULL,
    NUMBER    DNAME,
    ORDERKEY  DINTEGER_NOTNULL
);

CREATE TABLE GD_USER (
    ID        DINTKEY NOT NULL,
    USERNAME  DTEXT40,
    USERKEY   DINTEGER_NOTNULL
);

INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (1, 'Вход в программу пользователя');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (2, 'Выход из программы пользователя');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (3, 'Введен неверный пароль');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (4, 'Запуск программы');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (5, 'Закрытие программы');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (6, 'Создание нового заказа');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (7, 'Вход в просмотр заказов для оплаты');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (8, 'Вход в просмотр всех заказов (режим менеджера)');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (9, 'Вход в заказ');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (10, 'Сохранение заказа');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (11, 'Выход из заказа без сохранения');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (12, 'Печать пречека');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (13, 'Отмена пречека');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (14, 'Оплата заказа');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (15, 'Скидка карточкой');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (16, 'Скидка из справочника');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (17, 'Разделение заказа');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (18, 'Добавление товара в заказ');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (19, 'Увеличение количества товара в заказе');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (20, 'Уменьшение количества товара в заказе');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (21, 'Удаление товара из заказа');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (22, 'Ввод дробного количества товара');
INSERT INTO GD_EVENT (ID, EVENTNAME) VALUES (23, 'Ввод модификатора для товара');

COMMIT WORK;



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE GD_EVENT ADD CONSTRAINT GD_PK_EVENT PRIMARY KEY (ID);
ALTER TABLE GD_EVENTLOG ADD CONSTRAINT GD_PK_EVENTLOG PRIMARY KEY (ID);
ALTER TABLE GD_GOOD ADD CONSTRAINT GD_PK_GOOD PRIMARY KEY (ID);
ALTER TABLE GD_GOODLOG ADD CONSTRAINT GD_PK_GOODLOG PRIMARY KEY (ID);
ALTER TABLE GD_ORDER ADD CONSTRAINT GD_PK_ORDER PRIMARY KEY (ID);
ALTER TABLE GD_USER ADD CONSTRAINT GD_PK_USER PRIMARY KEY (ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE GD_EVENTLOG ADD CONSTRAINT FK_GD_EVENTLOG_EVENTKEY FOREIGN KEY (EVENTKEY) REFERENCES GD_EVENT (ID) ON UPDATE CASCADE;
ALTER TABLE GD_EVENTLOG ADD CONSTRAINT FK_GD_EVENTLOG_GOODLOGKEY FOREIGN KEY (GOODLOGKEY) REFERENCES GD_GOODLOG (ID) ON UPDATE CASCADE;
ALTER TABLE GD_EVENTLOG ADD CONSTRAINT FK_GD_EVENTLOG_ORDERKEY FOREIGN KEY (ORDERKEY) REFERENCES GD_ORDER (ID) ON UPDATE CASCADE;
ALTER TABLE GD_EVENTLOG ADD CONSTRAINT FK_GD_EVENTLOG_USERKEY FOREIGN KEY (USERKEY) REFERENCES GD_USER (ID) ON UPDATE CASCADE;
ALTER TABLE GD_GOODLOG ADD CONSTRAINT FK_GD_GOODLOG_GOODKEY FOREIGN KEY (GOODKEY) REFERENCES GD_GOOD (ID) ON UPDATE CASCADE;


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX GD_GOOD_IDX1 ON GD_GOOD (GOODKEY);
CREATE INDEX GD_ORDER_IDX1 ON GD_ORDER (ORDERKEY);
CREATE INDEX GD_USER_IDX1 ON GD_USER (USERKEY);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: GD_BI_EVENTLOG */
CREATE TRIGGER GD_BI_EVENTLOG FOR GD_EVENTLOG
ACTIVE BEFORE INSERT POSITION 0
AS 
 BEGIN 
   IF (NEW.ID IS NULL) THEN 
     NEW.ID = GEN_ID(gd_g_unique, 1); 
 END
^

/* Trigger: GD_BI_GOOD */
CREATE TRIGGER GD_BI_GOOD FOR GD_GOOD
ACTIVE BEFORE INSERT POSITION 0
AS 
 BEGIN 
   IF (NEW.ID IS NULL) THEN 
     NEW.ID = GEN_ID(gd_g_unique, 1); 
 END
^

/* Trigger: GD_BI_GOODLOG */
CREATE TRIGGER GD_BI_GOODLOG FOR GD_GOODLOG
ACTIVE BEFORE INSERT POSITION 0
AS 
 BEGIN 
   IF (NEW.ID IS NULL) THEN 
     NEW.ID = GEN_ID(gd_g_unique, 1); 
 END
^

/* Trigger: GD_BI_ORDER */
CREATE TRIGGER GD_BI_ORDER FOR GD_ORDER
ACTIVE BEFORE INSERT POSITION 0
AS 
 BEGIN 
   IF (NEW.ID IS NULL) THEN 
     NEW.ID = GEN_ID(gd_g_unique, 1); 
 END
^

/* Trigger: GD_BI_USER */
CREATE TRIGGER GD_BI_USER FOR GD_USER
ACTIVE BEFORE INSERT POSITION 0
AS 
 BEGIN 
   IF (NEW.ID IS NULL) THEN 
     NEW.ID = GEN_ID(gd_g_unique, 1); 
 END
^

SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON GD_EVENT TO ADMINISTRATOR;
GRANT ALL ON GD_EVENTLOG TO ADMINISTRATOR;
GRANT ALL ON GD_GOOD TO ADMINISTRATOR;
GRANT ALL ON GD_GOODLOG TO ADMINISTRATOR;
GRANT ALL ON GD_ORDER TO ADMINISTRATOR;
GRANT ALL ON GD_USER TO ADMINISTRATOR;
GRANT SELECT ON RDB$FORMATS TO PUBLIC;
GRANT SELECT ON RDB$PAGES TO PUBLIC;
GRANT SELECT ON RDB$ROLES TO PUBLIC;
